### ISSUE TITLE
Missing code

### ISSUE THREAD

**Issue by CliffCawley** [Microsoft/SmartHotel360-Sentiment-Analysis-App#1]
2 months ago you said:

`Note: This repo is under construction and within the next few days we will release the code and more details on this Readme. Please stay tuned!`

Any news on when it will be available?

**Comment by srivatsamarichi** [comment]
Any updates here?

**Comment by srivatsamarichi** [comment]
Is the code being added here?

**Comment by bradygmsft** [comment]
Sorry about the delay, @SrivatsaMarichi - we wanted to make sure all the code worked with updates that've been made since Connect();, and we wanted to craft a better readme that walks through the entire setup of everything this demo required. It's in here now, and we hope you enjoy it!
