### ISSUE TITLE
Unable to debug the azure functions app locally

### ISSUE THREAD

**Issue by srivatsamarichi** [Microsoft/SmartHotel360-Sentiment-Analysis-App#10]
When I try to run the function app locally, nothing shows up. Can anyone help me here?

This is what I see when I debug from the **Source/Function** directory.

![vscode_error](https://user-images.githubusercontent.com/13433045/47742922-bb013a80-dca3-11e8-8d8a-d29c2670d253.png)

**Comment by dsanchezcr** [comment]
Hi @SrivatsaMarichi! Thank you for letting us know about this issue. The settings for the debugging were missing. We fix it with the commit [049fa01](https://github.com/Microsoft/SmartHotel360-SentimentAnalysis/commit/049fa018dc464d16ae21535d40458cef9251ecd6). Please try it again!

**Comment by srivatsamarichi** [comment]
>I still get the error. I pulled the latest source code. This is what I get.

![functions error](https://user-images.githubusercontent.com/13433045/47765661-055cd880-dcf1-11e8-93a9-5be463a87c32.png)

**Comment by dsanchezcr** [comment]
Make sure you configured the dbconfig.js file without the protocol and port number and also have installed the extension for CosmosDB. The error I see in the binding is regarding that extension, make sure install it inside the AnalyzePendingTweet folder. Let me know if this works. Thanks!

**Comment by srivatsamarichi** [comment]
When I installed the extension inside the AnalyzePendingTweet directory and run, I still encounter the same issue with connection refused. I am not behind the proxy or firewall.

Extension Installation status.

![2018-10-31_14-54-25](https://user-images.githubusercontent.com/13433045/47778457-f12ed080-dd1c-11e8-8436-658c57149ef7.png)

Error encountered.

![2018-10-31_14-52-35](https://user-images.githubusercontent.com/13433045/47778403-d3616b80-dd1c-11e8-92b3-4539fc9cdc2d.png)

**Comment by dsanchezcr** [comment]
Did you also configured the local.settings.json file? The Azure Function needs the storage configuration. I faced this error before and restarting VS Code solved the issue since for some reason the process running before was blocking by the Windows Firewall.

**Comment by srivatsamarichi** [comment]
Yes, I have configured the same as per the guidelines. Don't know why I'm encountering the error still :-(
Is it something to do with the node version? The current version which I'm running is 10.13.0 LTS.
Every time I debug, I get the below error.

![2018-10-31_22-56-50](https://user-images.githubusercontent.com/13433045/47806713-666fc500-dd60-11e8-8258-e2ca6603204d.png)
