### ISSUE TITLE
running issues during extension installation

### ISSUE THREAD

**Issue by srivatsamarichi** [Microsoft/SmartHotel360-Sentiment-Analysis-App#3]
Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

PS C:\Users\srivatsam\Downloads\Sh360SA\src\functions> node -v
v8.9.4
PS C:\Users\srivatsam\Downloads\Sh360SA\src\functions> func extensions install --package Microsoft.Azure.WebJobs.Extensions.CosmosDB --version 3.0.0-beta6

                  %%%%%%
                 %%%%%%
            @   %%%%%%    @
          @@   %%%%%%      @@
       @@@    %%%%%%%%%%%    @@@
     @@      %%%%%%%%%%        @@
       @@         %%%%       @@
         @@      %%%       @@
           @@    %%      @@
                %%
                %

**Error: unknown argument extensions
Azure Functions Core Tools (1.0.8)
Function Runtime Version: 1.0.11510.0
Usage: func [context] [context] <action> [-/--options]**

Contexts:
azure      Commands to log in to Azure and manage resources
function   Commands for creating and running functions locally
host       Commands for running the Functions host locally
proxy      Commands for managing function proxies
settings   Commands for managing environment settings for the local Functions host
templates  Commands for listing available function templates

Actions:
new     Create a new function from a template. Aliases: new, create
    --language [-l] Template programming language, such as C#, F#, JavaScript, etc.
    --template [-t] Template name
    --name [-n]     Function name

init    Create a new Function App in the current folder. Initializes git repo.
    --no-source-control [-n] Skip running git init. Default is false.

run     Run a function directly
    <FunctionName> Function to run
    --timeout [-t]   Time (in seconds) to wait until local Functions host is ready
    --content [-c]   content to pass to the function, such as HTTP body
    --file [-f]      File name to use as content
    --debug [-d]     Attach a debugger to the host process before running the function
    --no-interactive Don't prompt or expect any stdin.

**Comment by bradygmsft** [comment]
@SrivatsaMarichi could you run this command and let me know what you get? I'd like to make sure I know what version of the func CLI you're using. 

```
npm ls -g --depth=0
```

**Comment by srivatsamarichi** [comment]
@bradygmsft I got this after running the above mentioned command.
```
Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

PS C:\Users\srivatsam\Downloads\Sh360SA\src\functions> npm ls -g --depth=0
C:\Users\srivatsam\AppData\Roaming\npm
+-- azure-functions-core-tools@1.0.8
+-- bower@1.8.2
+-- bower-update@0.2.0
+-- generator-sudo-application@0.1.8
+-- generator-team@0.3.8
+-- generator-team-services-extension@1.1.11
+-- generator-vsts@0.2.6
+-- gulp-cli@1.4.0
+-- npm@5.6.0
+-- npm-windows-upgrade@4.1.0
+-- update@0.7.4
+-- update-node@0.1.0
+-- webpack@3.10.0
`-- yo@2.0.1
```

**Comment by srivatsamarichi** [comment]
@bradygmsft The functions app worked now perfect. It was my bad that I had included **https://** in the **config.endpoint** property in the **dbconfig.js** due to which it was failing. Now that I have replaced, the graph is shown beautifully 😎

Also I was able to install the package **Microsoft.Azure.WebJobs.Extensions.CosmosDB --version 3.0.0-beta6** successfully. I guess due to the above error it was blocking me for adding the package.

Below are the 2 screenshots of my output for your reference. Let me know if this is how it's suppose to be.

## Gremlin Graph in Cosmos DB

![gremlin_graph](https://user-images.githubusercontent.com/13433045/36781845-258deb0e-1c9d-11e8-9ea9-d4b9a825dcb4.png)

## Azure Functions output in VS Code when tweeted
![functions_output](https://user-images.githubusercontent.com/13433045/36781922-5019a962-1c9d-11e8-90ef-32946ccd6c70.png)

**Comment by bradygmsft** [comment]
This is great to see. Glad things are working out. I will now close the issue, but should you see anything else pop up please don't hesitate to reach out with another issue. And as always, pull requests are awesome, too!
