### ISSUE TITLE
Unable to debug Azure Function locally

### ISSUE THREAD

**Issue by srivatsamarichi** [Microsoft/SmartHotel360-Sentiment-Analysis-App#8]
Hi @bradygmsft, I was trying to debug the azure function app locally and I ended up with the below error. Can you help me here?

![2018-07-20_16-39-33](https://user-images.githubusercontent.com/13433045/42999466-82271256-8c3b-11e8-9491-9b9a71e77646.jpg)

**Comment by dsanchezcr** [comment]
It should be fixed with commit [b135914](https://github.com/Microsoft/SmartHotel360-SentimentAnalysis/commit/b135914e9883dfb4ea45e08e506d504f6adbef06) one of the packages was out of date.
